sudo: false
language: python
python:
- '2.7'

cache:
  directories:
  - "$HOME/google_app_engine/"

env:
- API_CHECK=https://appengine.google.com/api/updatecheck

before_script:
# Idea from https://blog.bekt.net/p/gae-sdk/ retrieve GAE SDK
- SDK_VERSION=$(curl -s $API_CHECK | awk -F '\"' '/release/ {print $2}')
- SDK_URL=https://storage.googleapis.com/appengine-sdks/featured/google_appengine_$SDK_VERSION.zip
- wget $SDK_URL -nv
- unzip -q google_appengine_$SDK_VERSION.zip

before_install:
- mkdir -p lib

install:
# install dependencies

- pip install -r requirements.txt lib/

  
script:
#RUN THE TESTS
- nosetests --with-coverage --with-gae  --gae-lib-root=google_appengine   --cover-package=blog   tests/test_*
after_success:
- codecov
