runtime: python310
default_expiration: "10m"
entrypoint: gunicorn -b :8100 -w 2 blog:app

handlers:
- url: /favicon.ico
  static_files: blog/static/images/favicon.ico
  upload: blog/static/images/favicon.ico
  secure: always

- url: /robots.txt
  static_files: blog/static/robots.txt
  upload: blog/static/robots.txt
  secure: always

- url: /static
  static_dir: blog/static
  http_headers:
    expiration: "10m"
    Cache-Control:  must-revalidate 
  secure: always
- url: .*
  script: blog.app
  secure: always
- url: /edit
  script: blog.app
  login: admin
  secure: always

env_variables:
  GOOGLE_CLOUD_PROJECT: 'aarsakian'
  FIREBASE_PROJECT_ID: 'aarsakian'
  GOOGLE_APPLICATION_CREDENTIALS: 'aarsakian-1e9c52345507.json'


skip_files:
 - ^(.*/)?#.*#$
 - ^(.*/)?.*~$
 - ^(.*/)?.*\.py[co]$
 - ^(.*/)?.*/RCS/.*$
 - ^(.*/)?\..*$
 - google_appengine_*
 - virtualEnv*
 - cover*
 - scripts
 - ^(node_modules/.*)
 - ^(tests/.*)
