runtime: python312
default_expiration: "10m"
# The entrypoint should point to your 'blog.py' file's 'app' object
entrypoint: gunicorn -b :$PORT -w 2 blog:app

handlers:
- url: /favicon.ico
  static_files: blog/static/images/favicon.ico
  upload: blog/static/images/favicon.ico
  secure: always

- url: /robots.txt
  static_files: blog/static/robots.txt
  upload: blog/static/robots.txt
  secure: always

- url: /static
  static_dir: blog/static
  http_headers:
    Cache-Control: "public, max-age=600, must-revalidate"
  secure: always

# 'login: admin' requires 'script: auto' in Python 3
- url: /edit
  script: auto
  login: admin
  secure: always

# Catch-all handler must come last and use 'script: auto'
- url: .*
  script: auto
  secure: always

env_variables:
  GOOGLE_CLOUD_PROJECT: 'aarsakian'
  FIREBASE_PROJECT_ID: 'aarsakian'